DROP TABLE IF EXISTS TB_PEDIDO;
--DROP TABLE IF EXISTS TB_CLIENTE;
--DROP TABLE IF EXISTS TB_PRODUTO;
  
CREATE TABLE TB_PEDIDO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  id_cliente int(250) NOT NULL,
  id_produtos VARCHAR(250) NOT NULL,
  total_pedido DOUBLE(250) NOT NULL,
  end_entrega VARCHAR(250) NOT NULL
);
--CREATE TABLE TB_PRODUTO (
--  id INT AUTO_INCREMENT  PRIMARY KEY,
--  valor DOUBLE(250) NOT NULL  
--);
--CREATE TABLE TB_CLIENTE (
--  id INT AUTO_INCREMENT  PRIMARY KEY,
--  end_entrega VARCHAR(250) NOT NULL
--);

